# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

theme                   : minimal-mistakes-jekyll
minimal_mistakes_skin   : "iec"

# Site Settings
locale                  : "pt-BR"
title                   : Divisão de Ciência da Computação - IEC
title_separator         : "-"
name                    : ITA - IEC
email                   : your-email@ita.br
description: >- # '>-' means to ignore newlines until "baseurl:" see: https://yaml-multiline.info/
  Divisão de Ciência da Computação do Instituto Tecnológico de Aeronáutica
  (ITA) do Comando da Aeronáutica, São José dos Campos, São Paulo.
url                     : # the base hostname & protocol for your site, e.g. http://example.com
baseurl                 : # the subpath of your site, e.g. /blog
words_per_minute        : 300

search                  : true
search_provider         : google
google:
  search_engine_id      : 008045032394843368035:wbsj5hu7osg
  instant_search        : true

# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :


# Processing Files
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
include:
  - _pages
exclude:
  - third_party/minimal-mistakes/.editorconfig
  - third_party/minimal-mistakes/.gitattributes
  - third_party/minimal-mistakes/.github
  - third_party/minimal-mistakes/docs/
  - third_party/minimal-mistakes/test/
  - third_party/minimal-mistakes/CHANGELOG.md
  - third_party/minimal-mistakes/minimal-mistakes-jekyll.gemspec
  - third_party/minimal-mistakes/README.md
  - third_party/minimal-mistakes/screenshot-layouts.png
  - third_party/minimal-mistakes/screenshot.png
  - INSTALACAO.md
  - README.md
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Liquid
#strict_front_matter: true
#liquid:
#  error_mode: strict


# Conversion
#markdown: kramdown
#highlighter: rouge
#lsi: false
#excerpt_separator: "\n\n"
#incremental: false


# Markdown Processing
#kramdown:
#  input: GFM
#  hard_wrap: false
#  auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  smart_quotes: lsquo,rsquo,ldquo,rdquo
#  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
#  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Plugins (previously gems:)
plugins:
  - jekyll-feed

 
# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [development]


# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
