# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Divisão de Ciência da Computação - IEC
name: ITA - IEC
email: your-email@ita.br
description: >- # '>-' means to ignore newlines until "baseurl:" see: https://yaml-multiline.info/
  Divisão de Ciência da Computação do Instituto Tecnológico de Aeronáutica
  (ITA) do Comando da Aeronáutica, São José dos Campos, São Paulo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

search: true
search_provider: google
google:
  search_engine_id: 008045032394843368035:wbsj5hu7osg
  instant_search: true

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - third_party/minimal-mistakes/.editorconfig
  - third_party/minimal-mistakes/.gitattributes
  - third_party/minimal-mistakes/.github
  - third_party/minimal-mistakes/docs/
  - third_party/minimal-mistakes/test/
  - third_party/minimal-mistakes/CHANGELOG.md
  - third_party/minimal-mistakes/minimal-mistakes-jekyll.gemspec
  - third_party/minimal-mistakes/README.md
  - third_party/minimal-mistakes/screenshot-layouts.png
  - third_party/minimal-mistakes/screenshot.png
  - INSTALACAO.md
  - README.md
 